<!doctype html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-US">
<!--<![endif]-->
<!-- TODO: SUpprimer le formulaire Mettre notre contact Adresse email, page facebook, numéro de téléphone (utiliser les logos font awesome tel, facebook et mail) -->
<!-- TODO: Dans le pied de page changer le logo, changer le nom de l'entreprise, supprimer le "License" -->
<!-- TODO: Mettre la vidéo et virer bouton plus titre ne laisse que truc pour déscendre vers le bas -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Explore | Agence de digital marketing</title>
    <meta name="description" content="A free html template with Sketch design made with Bootstrap">
    <meta name="keywords" content="Une agence qu'elle est bien"/>
    <meta name="author" content="Explore"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon generated by https://realfavicongenerator.net/ -->
    <link rel="icon" type="image/png" href="img/favicon/favicon.ico" sizes="32x32"
    <link rel="manifest" href="img/favicon/manifest.json">
    <link rel="mask-icon" href="img/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="img/favicon/favicon.ico">
    <meta name="msapplication-TileColor" content="#66e0e5">
    <meta name="msapplication-TileImage" content="img/favicon/mstile-144x144.png">
    <meta name="msapplication-config" content="img/favicon/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <!-- end favicon links -->
    <link rel="stylesheet" href="css/bootstrap.min.css"/>
    <link rel="stylesheet" href="css/normalize.min.css">
    <link rel="stylesheet" href="css/animate.min.css">
    <link rel="stylesheet" href="css/flickity.min.css">
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

</head>

<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->
<div class="container-fluid">
    <div class="row">
        <div class="header-nav-wrapper">
            <div class="logo">
                <a href="/index.html"><img src="img/Logo_explore_blanc.png" alt="Synthetica Freebie"></a>
            </div>
            <div class="primary-nav-wrapper">
                <nav>
                    <ul class="primary-nav">
                        <li><a href="#team">L'equipe</a></li>
                        <li><a href="#freebies">Nos services</a></li>
                    </ul>
                </nav>
                <div class="secondary-nav-wrapper">
                    <ul class="secondary-nav">
                        <li class="subscribe"><a href="#contact">Contactez-nous</a></li>
                        <li class="search"><a href="#search" class="show-search"><i class="fa fa-search"></i></a></li>
                    </ul>
                </div>
                <div class="search-wrapper">
                    <ul class="search">
                        <li>
                            <input type="text" id="search-input" placeholder="Start typing then hit enter to search">
                        </li>
                        <li>
                            <a href="#" class="hide-search"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="navicon">
                <a class="nav-toggle" href="#"><span></span></a>
            </div>
        </div>
    </div>
</div>
<header class="hero">
    <!--<div class="carousel js-flickity">-->
    <div class="carousel-cell" style="background-image: url(img/Photoéquipe2019/1080p_4.gif);">
        <div class="hero-bg">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h1 class="wp1">Explore, agence de conseils digitale</h1>
                        <a href="#team" class="btn primary wp2">En savoir plus</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 hero-intro-text wp3">
                        <p>Notre équipe vous permettra <span class="bold italic">D'EXPLORER</span> les meilleures
                            solutions</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--</div>-->
    <div class='mouse-container'>
        <a href="#team">
            <div class='mouse'>
                <span class='scroll-down'></span>
            </div>
        </a>
    </div>
</header>
<!-- SECTION: Intro -->

<!-- END SECTION: Intro -->
<!-- SECTION: Crew -->
<section class="crew has-padding alternate-bg" id="team">
    <section class="crew has-padding alternate-bg" id="team">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h4 id="wteam"><i class="fa fa-rocket" aria-hidden="true"></i> L'equipe</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-sm-6 col-xs-12 pres">
                    <article class="crew-member" style="background-image: url(img/Photoéquipe2019/Dorian_Fraysse.png)">
                        <figure>
                            <figcaption class="overlay">
                                <h2>Dorian FRAYSSE</h2>
                                <p>Etudiant en B3 Ingesup et passioné de voitures et mécanique, j'aime également les
                                    nouvelles technologies, ansi que l'art.</p>
                                <div class="crew-socials">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12 pres">
                    <article class="crew-member" style="background-image: url(img/Photoéquipe2019/Hugo_Delouche.jpg)">
                        <figure>
                            <figcaption class="overlay">
                                <h2>Hugo DELOUCHE</h2>
                                <p>Etudiant en Audiovisuel, je suis passionné de montage et de post production.</p>
                                <div class="crew-socials">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12 pres">
                    <article class="crew-member" style="background-image: url(img/Photoéquipe2019/Hugo_Estruch.jpg)">
                        <figure>
                            <figcaption class="overlay">
                                <h2>Hugo ESTRUCH</h2>
                                <p>Étudiant en informatique a ynov, j'aime l'informatique et le jeu d'échec.</p>
                                <div class="crew-socials">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12 pres">
                    <article class="crew-member"
                             style="background-image: url(img/Photoéquipe2019/Miora_Rabenjamina.jpg)">
                        <figure>
                            <figcaption class="overlay">
                                <h2>Miora RABENJAMINA</h2>
                                <p>Etudiante en M1 direction artistique passionnée d'illustrations .</p>
                                <div class="crew-socials">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12 pres">
                    <article class="crew-member"
                             style="background-image: url(img/Photoéquipe2019/Dorianne_LE_DEUFF.jpg)">
                        <figure>
                            <figcaption class="overlay">
                                <h2>Dorianne LE DEUFF</h2>
                                <p>Etudiante en Bachelor 2 “Digital Business School”, passionnée d’anglais et de
                                    communication.</p>
                                <div class="crew-socials">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12 pres">
                    <article class="crew-member"
                             style="background-image: url(img/Photoéquipe2019/Landry_CHERUBIN-JEANNETTE.jpg)">
                        <figure>
                            <figcaption class="overlay">
                                <h2>Landry CHERUBIN-JEANNETTE</h2>
                                <p>Etudiant en mastère "Expert Cloud Sécurité et infrastructure", passioné de musique et
                                    de football</p>
                                <div class="crew-socials">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12 pres">
                    <article class="crew-member" style="background-image: url('img/thomas.jpg')">
                        <figure>
                            <figcaption class="overlay">
                                <h2>Thomas MIRABILE</h2>
                                <p>Etudiant en Master Informatique, je suis passionné par le sport, la musique et le
                                    digital.</p>
                                <div class="crew-socials">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12 pres">
                    <article class="crew-member" style="background-image: url(img/Photoéquipe2019/Victor_GRANIER.jpg)">
                        <figure>
                            <figcaption class="overlay">
                                <h2>Victor GRANIER</h2>
                                <p>Etudiant en B1 Ingesup, passioné de jeux vidéo, de Powerlifting et de Cinema.</p>
                                <div class="crew-socials">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12 pres">
                    <article class="crew-member" style="background-image: url(img/Photoéquipe2019/Siva_MANOGARAME.png)">
                        <figure>
                            <figcaption class="overlay">
                                <h2>Siva MANOGARAME</h2>
                                <p>Etudiant en B3 ESSCA, passionné du marketing et du digital.</p>
                                <div class="crew-socials">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
            </div>
            <div class="row skillset">
                <div class="col-md-6">
                    <div class="bar-chart-wrapper">
                        <h5 class="bar-chart-text">Experience Design <span class="push-right">90%</span></h5>
                        <div class="bar-wrapper">
                            <div class="bar" data-percentage="90%">
                                <span></span>
                            </div>
                        </div>
                    </div>

                    <div class="bar-chart-wrapper">
                        <h5 class="bar-chart-text">Digital Marketing<span class="push-right">95%</span></h5>
                        <div class="bar-wrapper">
                            <div class="bar" data-percentage="95%">
                                <span></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="bar-chart-wrapper">
                        <h5 class="bar-chart-text">Interactive Prototyping <span class="push-right">80%</span></h5>
                        <div class="bar-wrapper">
                            <div class="bar" data-percentage="80%">
                                <span></span>
                            </div>
                        </div>
                    </div>
                    <div class="bar-chart-wrapper">
                        <h5 class="bar-chart-text">Visual Design <span class="push-right">90%</span></h5>
                        <div class="bar-wrapper">
                            <div class="bar" data-percentage="90%">
                                <span></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="bar-chart-wrapper">
                        <h5 class="bar-chart-text">Success Maker <span class="push-right">100%</span></h5>
                        <div class="bar-wrapper">
                            <div class="bar" data-percentage="100%">
                                <span></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="bar-chart-wrapper">
                        <h5 class="bar-chart-text">Communication <span class="push-right">80%</span></h5>
                        <div class="bar-wrapper">
                            <div class="bar" data-percentage="80%">
                                <span></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>

</section>
<!-- END SECTION: Crew -->
<!-- SECTION: Stats -->
<div class="stats has-padding-tall">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4 stats-container">
                <i class="icon icon-Arrow"></i>
                <div class="stats-wrapper">
                    <p class="stats-number" data-stop="24">24</p>
                    <p class="stats-text">Analyse stratégie marketing</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 stats-container">
                <i class="icon icon-Book"></i>
                <div class="stats-wrapper">
                    <p class="stats-number" data-stop="341">341</p>
                    <p class="stats-text">Conseil et formation</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 stats-container">
                <i class="icon icon-Pen"></i>
                <div class="stats-wrapper">
                    <p class="stats-number" data-stop="43">43</p>
                    <p class="stats-text">Créativité-identité graphique</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END SECTION: Stats -->
<!-- SECTION: Articles -->

<!-- END SECTION: Articles -->
<!-- SECTION: Freebies -->
<section class="freebies has-padding" id="freebies">
    <div class="container freebies-intro" class="freebie2">
        <div class="row">
            <div class="col-md-12">
                <h4><i class="fa fa-rocket" aria-hidden="true"></i> Nos services</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 content-left">
                <p>L’exploration de solutions digitales et novatrices pour nos clients constitue notre cœur de métier.
                    Chacune de nos solutions s’adapte aux besoins des clients, du conseil stratégique à la communication
                    visuelle en
                    passant par le développement de solutions informatique et le marketing.</p>
            </div>
            <div class="col-md-6 content-right">
                <p>Explore c’est avant tout une équipe qui s’engage à vous accompagner dans le changement. Conscient de
                    l’importance du numérique et de la technique dans la communication des entreprises, nous mettons
                    l’accent sur l’innovation et la créativité.</p>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 no-padding">
                <article class="item wp5">
                    <figure class="has-overlay" id="redbull">
                        <figcaption class="overlay">
                            <div class="like-share-wrapper">
                                <ul>
                                    <li>
                                        <div class="like-button-wrapper">
                                            <a href="#" class="like_button"><i
                                                    class="like-counter fa fa-heart-o"></i></a>
                                            <span class="count">0</span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="freebie-content">
                                <span class="date">29/01/2019</span>
                                <h2>Dossier Blast</h2>
                                <div class="group">
                                    <a href="https://tympanus.net/codrops/2015/08/11/freebie-sedna-one-page-website-template/"
                                       class="btn secondary">Download</a>
                                </div>
                            </div>
                        </figcaption>
                        <img src="img/Blast_arena-1.jpg" alt="Land.io Freebie" id="imgred">
                    </figure>
                </article>
            </div>
            <!--<div class="col-md-6 no-padding">
                <article class="item wp6">
                    <figure class="has-overlay">
                        <figcaption class="overlay">
                            <div class="like-share-wrapper">
                                <ul>
                                    <li>
                                        <div class="like-button-wrapper">
                                            <a href="#" class="like_button"><i class="like-counter fa fa-heart-o"></i></a>
                                            <span class="count">0</span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="freebie-content">
                                <span class="date">03/01/2016</span>
                                <h2>DoodleArt</h2>
                                <div class="group">
                                    <a href="https://tympanus.net/codrops/2015/09/16/freebie-land-io-ui-kit-landing-page-design-sketch/" class="btn secondary">Download</a>
                                </div>
                            </div>
                        </figcaption>
                        <img src="img/doodleeart02.png" alt="Land.io Freebie">
                    </figure>
                </article>
            </div>
        </div>-->
            <div class="row">
                <div class="col-md-6 no-padding">
                    <article class="item wp7">
                        <figure class="has-overlay">
                            <figcaption class="overlay">
                                <div class="like-share-wrapper">
                                    <ul>
                                        <li>
                                            <div class="like-button-wrapper">
                                                <a href="#" class="like_button"><i
                                                        class="like-counter fa fa-heart-o"></i></a>
                                                <span class="count">0</span>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div class="freebie-content">
                                    <span class="date">03/01/2016</span>
                                    <h2>A venir</h2>
                                    <div class="group">
                                        <a href="https://tympanus.net/codrops/?p=26570"
                                           class="btn secondary">Download</a>
                                    </div>
                                </div>
                            </figcaption>
                            <img src="img/freebie-03.jpg" alt="Synthetica Freebie">
                        </figure>
                    </article>
                </div>
                <div class="col-md-6 no-padding">
                    <article class="item wp8">
                        <figure class="has-overlay">
                            <figcaption class="overlay">
                                <div class="like-share-wrapper">
                                    <ul>
                                        <li>
                                            <div class="like-button-wrapper">
                                                <a href="#" class="like_button"><i
                                                        class="like-counter fa fa-heart-o"></i></a>
                                                <span class="count">0</span>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div class="freebie-content">
                                    <span class="date">03/01/2016</span>
                                    <h2>A venir</h2>
                                    <div class="group">
                                        <a href="#" class="btn secondary">Download</a>
                                    </div>
                                </div>
                            </figcaption>
                            <img src="img/freebie-04.jpg" alt="Synthetica">
                        </figure>
                    </article>
                </div>


                <!--BOUTON MODAL -->
                <!-- Button trigger modal -->
                <div class="container">
                    <div class="row" id="titrecontact">
                        <div class="col-md-12">
                            <h4><i class="fa fa-rocket" aria-hidden="true"></i> Nous contacter</h4>
                        </div>
                    </div>
                </div>
                <div class="row" id="maRowContact">
                    <div class="col-lg-offset-3 col-lg-2 col-md-12 col-sm-12 col-xs-12">
                        <div class="form-group spaceForm"> <!-- Email field -->
                            <label class="control-label requiredField" for="email">Email <i class="fa fa-envelope"
                                                                                            aria-hidden="true"></i><br/></p>
                                <a class="Lyen" href="mailto:explore.pro.international@gmail.com?subject=feedback">
                                    explore.pro.international@gmail.com</a></label>
                        </div>
                    </div>
                    <div class="col-lg-offset-1 col-lg-2 col-md-12 col-sm-12 col-xs-12">
                        <div class="form-group spaceForm"> <!-- Email field -->
                            <label class="control-label requiredField" for="email">Facebook <i
                                    class="fa fa-facebook" aria-hidden="true"></i><br/></p> <a class="Lyen"
                                                                                               href="https://www.facebook.com/Explore-International-Agency-1997894456972598">
                                Explore</a></label>
                        </div>
                    </div>
                    <div class=" col-lg-2 col-md-12 col-sm-12 col-xs-12">
                        <div class="form-group spaceForm"> <!-- Email field -->
                            <label class="control-label requiredField" for="email">Téléphone <i
                                    class="fa fa-phone" aria-hidden="true"></i><br/></p> <a class="Lyen"
                                                                                            href="06 59 79 28 63">
                                <i class="fa fa-phone-square" aria-hidden="true"></i>06 59 79 28 63 </a></label>
                        </div>
                    </div>
                    <div class="col-lg-offset-3 col-lg-12 col-md-hidden mapy"><br/><br/><br/><br/><br/>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2892.9825850571606!2d5.430548251050261!3d43.52355587902346!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12c98d74265acee7%3A0x8fd04d3389cc5dbb!2s2+Rue+le+Corbusier%2C+13100+Aix-en-Provence!5e0!3m2!1sfr!2sfr!4v1490122862473"
                                width="950" height="414" frameborder="0" style="border:0;"
                                allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div>
</section>
<!-- END SECTION: Freebies -->
<!-- SECTION: Get started -->

<!-- END SECTION: Get started -->
<!-- SECTION: Footer -->
<footer class="has-padding footer-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-4 footer-branding">
                <img class="footer-branding-logo" src="img/Logo_explore_blanc.png"
                     alt="Synthetica freebie html5 css3 template logo">
                <p>Website template created exclusively for <a href="https://tympanus.net/codrops/"><em>Explore</em></a>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 footer-nav">
                <ul class="footer-primary-nav">
                    <li><a href="#team">L'equipe</a></li>
                    <li><a href="#freebies">Nos services</a></li>
                </ul>
                <ul class="footer-share">
                    <li><a href="#" class="share-trigger"><i class="fa fa-share"></i>Share</a></li>
                </ul>
                <div class="share-dropdown">
                    <ul>
                        <li><a href="#" class="share-twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" class="share-facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" class="share-linkedin"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
                <ul class="footer-secondary-nav">
                    <li><p>Website template created exclusively for <a
                            href="https://tympanus.net/codrops/"><em>Explore</em></a></p></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-- END SECTION: Footer -->
<!-- JS CDNs -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
<script src="https://vjs.zencdn.net/5.4.6/video.min.js"></script>
<!-- jQuery local fallback -->
<script>
    window.jQuery || document.write('<script src="js/min/jquery-1.11.2.min.js"><\/script>')
</script>
<!-- JS Locals -->
<script src="js/min/bootstrap.min.js"></script>
<script src="js/min/modernizr-2.8.3-respond-1.4.2.min.js"></script>
<script src="js/min/retina.min.js"></script>
<script src="js/min/jquery.waypoints.min.js"></script>
<script src="js/min/flickity.pkgd.min.js"></script>
<script src="js/min/scripts-min.js"></script>
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID and uncomment -->
<!--
<script>
(function(b, o, i, l, e, r) {
    b.GoogleAnalyticsObject = l;
    b[l] || (b[l] =
        function() {
            (b[l].q = b[l].q || []).push(arguments)
        });
    b[l].l = +new Date;
    e = o.createElement(i);
    r = o.getElementsByTagName(i)[0];
    e.src = '//www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e, r)
}(window, document, 'script', 'ga'));
ga('create', 'UA-XXXXX-X', 'auto');
ga('send', 'pageview');
</script>
-->
</body>

</html>
